server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://192.168.56.61:3307/eyedb
    username: root
    password: 8z63s58rq04
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: 192.168.56.61
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.amqp: DEBUG
    root: info


# RabbitMQ queue, exchange, routing-key ??
rabbitmq:
  queue.name: sample.queue
  exchange.name: sample.exchange
  routing.key: sample.key